### ISSUE TITLE
More/stacked area line chart for member counts?

### ISSUE THREAD

**Issue by frollard** [Protospace/spaceport#18]
https://github.com/Protospace/spaceport/blob/d0402ea3882c50e4790beb6696282e531c2b13b3/webclient/src/Charts.js#L55

Not sure if membercount returns enough useful information to make it painless - is it possible to show the membercount broken down by stacked area - 
(pre)paid green
due/grace yellow
vacation grey
expired-within-the-last-month red?
Possible problem: If we use vanilla "expired" then that area would just grow forever and not be super useful. If we only look at the expired within the last month (or three) then we could see a snapshot of what is trending.

**Comment by tannercollin** [comment]
I could make a stacked graph of the following: overdue, due, and current/prepaid. Vacation is the same as being paused / expired / former member, there's no easy way to discern.

You are right about the expired counts not being able to stack and continuing to climb. It's also difficult to tell when they expired because after being three months past their expire date (overdue for two months), their paused date gets set to their expire date.

The reason the paused date gets set to their expire date is because it reflects the actual duration of their membership (what they paid for).

I don't see stacking overdue, due, and current/prepaid counts being worth the effort, especially since the overdue+due count is just the difference between the two lines.

It might be worth adding a monthly expired count bar chart to the sign up count bar chart though. It would simply be the number of members whose paused date is within each month. What do you think?

**Comment by frollard** [comment]
Perhaps...was just a thought on breaking down the proportion of the membership in each phase to see trends - are more people switching to pause, more people falling behind, etc. That way we can gauge what, if any actions we take versus the metrics. Run fb ad, see result (currently useful with the signups bar chart). Pandemic, membership dwindles - how many paused versus quit, etc.

I totally understand that the definitions are fuzzy especially on paused since the date is moved. It would probably involve a query to the 'count of pause request transactions in a given time frame' since the audit logs do track the transaction history - even if the actual count isn't a 'real' metric.

**Comment by tannercollin** [comment]
I've added vetted and retained member counts to the signup chart.

I'll have to think more on how to display the egress amounts. For now the decrease in the line chart can be used.
